package constants

const (
	SPLINTER_PATH     = "SPLINTER_PATH"
	SPLINTER_DRIVER   = "SPLINTER_DRIVER"
	SPLINTER_HOST     = "SPLINTER_HOST"
	SPLINTER_PORT     = "SPLINTER_PORT"
	SPLINTER_USER     = "SPLINTER_USER"
	SPLINTER_PASSWORD = "SPLINTER_PASSWORD"
	SPLINTER_DATABASE = "SPLINTER_DATABASE"
)
